### ISSUE TITLE
similarity === 0 je cim ina ?

### ISSUE THREAD

**Issue by tu1ly** [vendybike/topMonks#5]
https://github.com/vendybike/topMonks/blob/8e2d11e5504bc5809a78c6d0769db1985de749be/index.js#L14

**Comment by vendybike** [comment]
Nevim, jestli chapu dobre tuto otazku, ale jestlize hledam prvek s nejvetsi shodou a 1 je teda nejvetsi maximalni shoda, nemusim tedy dal prochazet, zapisu tento prvek a zkoncim prochazeni. Kdyby tam byla 0, tak nasledujici prvek muze byt vetsi.

**Comment by tu1ly** [comment]
pravda - moja chyba - nechal som sa strhnut optimalizaciami :)
